version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: axenix_conf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d axenix_conf"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/config/dev.yaml
      DATABASE_DSN: postgres://postgres:postgres@postgres:5432/axenix_conf?sslmode=disable
      DATABASE_AUTO_MIGRATE: "true"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
